version: '3.8'

services:
  nordvpn-dashboard:
    build: .
    container_name: nordvpn-dashboard
    network_mode: host
    user: root
    environment:
      - PORT=4722
    volumes:
      - /usr/bin/nordvpn:/usr/bin/nordvpn
      - /run/nordvpn:/run/nordvpn
    privileged: true
    restart: unless-stopped
