version: '3.8'

services:
  nordvpn-dashboard:
    build: .
    container_name: nordvpn-dashboard
    network_mode: host
    environment:
      - PORT=4722
    restart: unless-stopped
    volumes:
      - /usr/bin/nordvpn:/usr/bin/nordvpn:ro
      - /usr/sbin/nordvpn:/usr/sbin/nordvpn:ro
    privileged: true

